Script started on Mon 30 Jan 2017 10:47:57 AM EST
(student)~/3490% ls
Foo.java  typescript
(student)~/3490% emacs typescript
[?1049h[?12;25h[?1h=[H[2J[52d[K[?1l>[?12l[?25h[?1049l[39;49m[?1049h[?12;25h[?1h=[>0c[H[2J[52d[K[H[?25l[7mFile Edit Options Buffers Tools Lisp-Interaction Help                                                                                                         [0m[39;49m[27m
[A
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[30m[48;5;250m-UUU:----F1  [39;49m[1m[30m[48;5;250m*scratch*   [0m[39;49m[30m[48;5;250m   All L1     (Lisp Interaction) ----------------------------------------------------------------------------------------------------[39;49m
[A[2d[?12l[?25h[?12;25h[52d[?25lFor information about GNU Emacs and the GNU system, type C-h C-a.[H
[?12l[?25h[?12;25h[52d[?25lFor information about GNU Emacs and the GNU system, type C-h C-a.[K[H[7mFile Edit Options Buffers Tools Help                                                                                                                          [0m[39;49m[27m
[A
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[30m[48;5;250m-UUU:----F1  [39;49m[1m[30m[48;5;250mtypescript  [0m[39;49m[30m[48;5;250m   All L1     (Fundamental) ---------------------------------------------------------------------------------------------------------[39;49m
[A[2d[?12l[?25h[?12;25h[52d[?25lBeginning of buffer[K[H
[?12l[?25h[?12;25h[52d[?25lEnd[6P[H
[?12l[?25h[?12;25h[52d[K[2d[52d[?25l(No files need saving)[H
[?12l[?25h[?12;25h[52d[K[?1l>[?12l[?25h[?1049l[39;49m(student)~/3490% cat Foo.java
class Foo{}
(student)~/3490% javac Foo.java
(student)~/3490% exit
exit

Script done on Mon 30 Jan 2017 10:48:49 AM EST
